<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13459" started-at="2017-07-11T10:55:42Z" finished-at="2017-07-11T10:55:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13459" started-at="2017-07-11T10:55:42Z" finished-at="2017-07-11T10:55:56Z">
      <class name="testcases.TestCalculator">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TestCalculator@1794d431]" name="setUp" is-config="true" duration-ms="6224" started-at="2017-07-11T12:55:42Z" finished-at="2017-07-11T12:55:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="StartApplication()[pri:0, instance:testcases.TestCalculator@1794d431]" name="StartApplication" duration-ms="3985" started-at="2017-07-11T12:55:49Z" finished-at="2017-07-11T12:55:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartApplication -->
        <test-method status="FAIL" signature="testBaufinanzierung_Antrag_Start()[pri:1, instance:testcases.TestCalculator@1794d431]" name="testBaufinanzierung_Antrag_Start" duration-ms="860" started-at="2017-07-11T12:55:53Z" finished-at="2017-07-11T12:55:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Commerzbank Finanzierungsanfrage> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Commerzbank Finanzierungsanfrage> but was:<>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Start(TestCalculator.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBaufinanzierung_Antrag_Start -->
        <test-method status="FAIL" signature="testBaufinanzierung_Antrag_Zinsen_Check()[pri:2, instance:testcases.TestCalculator@1794d431]" name="testBaufinanzierung_Antrag_Zinsen_Check" duration-ms="1687" started-at="2017-07-11T12:55:54Z" finished-at="2017-07-11T12:55:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Angaben zu Ihrer Finanzierung> but was:<Zinscheck>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Angaben zu Ihrer Finanzierung> but was:<Zinscheck>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Zinsen_Check(TestCalculator.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBaufinanzierung_Antrag_Zinsen_Check -->
        <test-method status="FAIL" signature="testBaufinanzierung_Antrag_Persoenlichen_Daten()[pri:3, instance:testcases.TestCalculator@1794d431]" name="testBaufinanzierung_Antrag_Persoenlichen_Daten" duration-ms="78" started-at="2017-07-11T12:55:55Z" finished-at="2017-07-11T12:55:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Angaben zu Ihrer Finanzierung> but was:<Persönliche Angaben>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Angaben zu Ihrer Finanzierung> but was:<Persönliche Angaben>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Persoenlichen_Daten(TestCalculator.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBaufinanzierung_Antrag_Persoenlichen_Daten -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TestCalculator@1794d431]" name="tearDown" is-config="true" duration-ms="594" started-at="2017-07-11T12:55:55Z" finished-at="2017-07-11T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TestCalculator -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
